# Google App Engine configuration (Alternative to Cloud Run)
runtime: python310

# Environment variables
env_variables:
  FLASK_ENV: production
  # Add your Reddit API credentials here if needed
  # REDDIT_CLIENT_ID: "your_client_id"
  # REDDIT_CLIENT_SECRET: "your_client_secret"
  # REDDIT_USER_AGENT: "portfolio_analyzer_1.0"

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2