# Docker Compose for Production - Multi-User Portfolio Analyzer
# Simple production setup with SQLite and persistent volumes
version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    container_name: portfolio-analyzer-prod
    ports:
      - "8080:8080"
    volumes:
      # Persist database and uploads across container restarts
      - portfolio_data:/app/data
      - portfolio_uploads:/app/uploads
    environment:
      # Production settings
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PORT=8080
      # API keys (set these via environment or secrets)
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-demo}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-demo}
      # Security (change in production)
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-me}
      # Logging
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  portfolio_data:
    driver: local
  portfolio_uploads:
    driver: local

networks:
  default:
    name: portfolio-prod-network